//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.01 at 11:53:55 PM EST 
//


package edu.stevens.cs548.clinic.service.web.rest.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import edu.stevens.cs548.clinic.service.web.rest.PatientRepresentation;
import edu.stevens.cs548.clinic.service.web.rest.ProviderRepresentation;
import edu.stevens.cs548.clinic.service.web.rest.TreatmentRepresentation;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.stevens.cs548.clinic.service.web.rest.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PatientRepresentation_QNAME = new QName("http://cs548.stevens.edu/clinic/service/web/rest/dap", "patient-representation");
    private final static QName _TreatmentRepresentation_QNAME = new QName("http://cs548.stevens.edu/clinic/service/web/rest/dap", "treatment-representation");
    private final static QName _ProviderRepresentation_QNAME = new QName("http://cs548.stevens.edu/clinic/service/web/rest/dap", "provider-representation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.stevens.cs548.clinic.service.web.rest.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DrugType }
     * 
     */
    public DrugType createDrugType() {
        return new DrugType();
    }

    /**
     * Create an instance of {@link TreatmentType }
     * 
     */
    public TreatmentType createTreatmentType() {
        return new TreatmentRepresentation();
    }

    /**
     * Create an instance of {@link PatientType }
     * 
     */
    public PatientType createPatientType() {
        return new PatientRepresentation();
    }

    /**
     * Create an instance of {@link RadiologyType }
     * 
     */
    public RadiologyType createRadiologyType() {
        return new RadiologyType();
    }

    /**
     * Create an instance of {@link ProvierType }
     * 
     */
    public ProvierType createProvierType() {
        return new ProviderRepresentation();
    }

    /**
     * Create an instance of {@link LinkType }
     * 
     */
    public LinkType createLinkType() {
        return new LinkType();
    }

    /**
     * Create an instance of {@link SurgeryType }
     * 
     */
    public SurgeryType createSurgeryType() {
        return new SurgeryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PatientType }{@code >}}
     * 
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    @XmlElementDecl(namespace = "http://cs548.stevens.edu/clinic/service/web/rest/dap", name = "patient-representation")
    public JAXBElement<PatientType> createPatientRepresentation(PatientType value) {
        return new JAXBElement<PatientType>(_PatientRepresentation_QNAME, ((Class) PatientRepresentation.class), null, ((PatientRepresentation) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TreatmentType }{@code >}}
     * 
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    @XmlElementDecl(namespace = "http://cs548.stevens.edu/clinic/service/web/rest/dap", name = "treatment-representation")
    public JAXBElement<TreatmentType> createTreatmentRepresentation(TreatmentType value) {
        return new JAXBElement<TreatmentType>(_TreatmentRepresentation_QNAME, ((Class) TreatmentRepresentation.class), null, ((TreatmentRepresentation) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProvierType }{@code >}}
     * 
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
	@XmlElementDecl(namespace = "http://cs548.stevens.edu/clinic/service/web/rest/dap", name = "provider-representation")
    public JAXBElement<ProvierType> createProviderRepresentation(ProvierType value) {
        return new JAXBElement<ProvierType>(_ProviderRepresentation_QNAME, ((Class) ProviderRepresentation.class), null, ((ProviderRepresentation) value));
    }

}
