//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.01 at 11:53:55 PM EST 
//


package edu.stevens.cs548.clinic.service.web.rest.data;

import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SurgeryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SurgeryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="surgeon_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date_of_surgery" type="{http://www.w3.org/2001/XMLSchema}date" form="qualified"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SurgeryType", propOrder = {
    "surgeonName",
    "dateOfSurgery"
})
public class SurgeryType {

    @XmlElement(name = "surgeon_name", required = true)
    protected String surgeonName;
    @XmlElement(name = "date_of_surgery", namespace = "http://cs548.stevens.edu/clinic/service/web/rest/dap", required = true, type = String.class)
    @XmlJavaTypeAdapter(Adapter1 .class)
    @XmlSchemaType(name = "date")
    protected Date dateOfSurgery;

    /**
     * Gets the value of the surgeonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurgeonName() {
        return surgeonName;
    }

    /**
     * Sets the value of the surgeonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurgeonName(String value) {
        this.surgeonName = value;
    }

    /**
     * Gets the value of the dateOfSurgery property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Date getDateOfSurgery() {
        return dateOfSurgery;
    }

    /**
     * Sets the value of the dateOfSurgery property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfSurgery(Date value) {
        this.dateOfSurgery = value;
    }

}
